version: 0.2

env:
  variables:
    SECRET_NAME: "docker_cred"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Updating package lists and installing jq..."
      - yum update -y
      - yum install -y jq
      - echo "Installing Python dependencies..."
      - pip install --no-cache-dir -r requirements.txt
      - pip install pytest
      - echo "Retrieving Docker Hub credentials from Secrets Manager using SECRET_NAME..."
      - export DOCKER_CRED=$(aws secretsmanager get-secret-value --secret-id $SECRET_NAME --query SecretString --output text)
      - export DOCKER_HUB_USERNAME=$(echo $DOCKER_CRED | jq -r .DOCKER_HUB_USERNAME)
      - export DOCKER_HUB_PASSWORD=$(echo $DOCKER_CRED | jq -r .DOCKER_HUB_PASSWORD)
      - echo "Logging into Docker Hub..."
      - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  pre_build:
    commands:
      - echo "Running tests with pytest..."
      - pytest Project_Folder/test_model.py
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t binit13/aws-final-app:latest .
  post_build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push binit13/aws-final-app:latest

artifacts:
  files:
    - Dockerrun.aws.json
    - .ebextensions/**/*